### ISSUE TITLE
运行后好像没有生成最后的Typora.exe

### ISSUE THREAD

**Issue by 1321000350** [Cherno-x/dataBrawl#3]
![VeryCapture_20240424104757](https://github.com/Cherno-x/dataBrawl/assets/72781724/f978d684-f757-488d-b9d4-239e72046562)
运行后好像没有生成最后的Typora.exe，是哪里少了什么操作吗

**Comment by Cherno-x** [comment]
-i 选项不是生成地址的选项，具体可以-h查看具体命令
