### ISSUE TITLE
远程360一执行就杀，该怎么改

### ISSUE THREAD

**Issue by yangxixx** [Cherno-x/dataBrawl#4]

**Comment by Cherno-x** [comment]
请补充拦截详情。

**Comment by yangxixx** [comment]
![1111test](https://github.com/Cherno-x/dataBrawl/assets/77321474/621f0ac4-692f-46b2-b7a3-34b7c272eb2f)
一运行，服务器还没收到请求，就被查杀了。我估计是下载得那个windos api问题

**Comment by Cherno-x** [comment]
QVM是静态查杀，可以通过更换资源信息、添加伪签名等方式进行绕过，后续会优化编译器设置，减少QVM拦截情况。

**Comment by yangxixx** [comment]
![test22221](https://github.com/Cherno-x/dataBrawl/assets/77321474/3510e3cf-4059-4c98-8fc5-b35173e95646)
我把静态过了，这又咋过
